### PR TITLE
Allow casting to number

### PR DESCRIPTION
**Pull request by LayZeeDK**
Allow cast(variable, "number")

### CODE REVIEW

**Comment by Yevano** [comment]
`Object:opEq` calls `Object:equals`, which `String` overrides.

**Comment by LayZeeDK** [comment]
I see, good to know. I'm working on a Turtle API, built using SEE. Are you able to extend native tables (such as turtle)?

**Comment by Yevano** [comment]
In what way do you want to "extend" it?

**Comment by LayZeeDK** [comment]
Making native `turtle` methods available on my custom `Turtle` class, like setting metatable. Is there a SEE way to extend native tables in that way?

**Pull request merged**
