### PR TITLE
Fixed System.read function

### PR DESCRIPTION
**Pull request by SquidDev**
This is a re-implementation of the read function from bios.lua. Supports replacement characters, history, paste etc...

### CODE REVIEW

**Comment by SquidDev** [comment]
I'm going to have to rollback the last commit. Now I realise why Dan200 writes mods and I don't!

**Comment by Yevano** [comment]
Why port over the entire function? You should just cast the parameters and pass them to the native function.

**Comment by SquidDev** [comment]
The read function relies on os.pullEvent. This doesn't appear to work in SEE (this is the same reason Rednet doesn't work) and so needs to be ported .

**Comment by Yevano** [comment]
Ah, I see.

**Pull request merged**
